### ISSUE TITLE
Synthea Generic Module Generation from Symcat - Issue with the number of generated diseases

### ISSUE THREAD

**Issue by afansi** [teliov/symcat-to-synthea#1]
Hi,
Running your code on the Symcat dataset, it results into 650 Generic modules while the Symcat dataset contains 801 diseases. Why this difference occurs?

**Comment by teliov** [comment]
@afansi , the code drops modules which do not have symptoms. No point modelling conditions without symptoms.

**Comment by teliov** [comment]
@afansi , went through the csv file to confirm the conditions missing symptoms and found a difference in the way the csv file captured those conditions. Updated the parser to handle.

Thanks for pointing out!
