### ISSUE TITLE
From Odd Values to Probabilities

### ISSUE THREAD

**Issue by afansi** [teliov/symcat-to-synthea#2]
Hi,
I think there is a bug in your code when you are trying to compute the probability of the age, sex,and race given the corresponding odd values from the symcat csv file.

Instead of summing the odd values for all the different categories and multiply the result by 10 from which you next compute the probability, you can instead do the following:
prob = odd_value / (1 + odd_value)

As referred by this link: https://www.graphpad.com/support/faq/probability-vs-odds/.

Regards,

**Comment by teliov** [comment]
Thanks a lot!

That does make sense.
