### ISSUE TITLE
Request for Collaboration

### ISSUE THREAD

**Issue by afansi** [teliov/symcat-to-synthea#5]
Hi @teliov , is it possible to add me as a collaborator to this project. I have made some improvement over your code base and I would like you to review them through Pull Requests.

Basically, What I did so far consists of the following:
- Modifying the parse.py file to collect additional information when parsing the symtom csv file
- Modify the generate.py file to generate better look-alike graphs (the hint here was to start with the gender, the race, before diving into conditioning on the age (with loops eventually as it evolves through time) and symptoms. You can view the difference between different version by viewing the attached files in the Synthea Generic Module Builder (https://synthetichealth.github.io/module-builder/). Please, remove the ".txt" extension before uploading them in the module builder.
[abdominal-hernia.json.txt](https://github.com/teliov/symcat-to-synthea/files/4294223/abdominal-hernia.json.txt)
[abdominal-hernia_new.json.txt](https://github.com/teliov/symcat-to-synthea/files/4294224/abdominal-hernia_new.json.txt)

- Adding unit-tests.

I am eager to share that with you. 

Regards.

**Comment by teliov** [comment]
Hi @afansi ,

I checked out the new generated module format and I do agree. It does make sense to position the Age lower in the decision tree (especially since it is the only one of the parameters that will change as the clock ticks).

I'll add you as a collaborator and looking forward to the PR!

**Comment by teliov** [comment]
Also @afansi , if you've got some time to chat a bit about the project, that would be great! 
I missed you at the introductory meeting with Alexis and Louis-Philippe.

**Comment by afansi** [comment]
Hi @teliov ,
That wont be a problem. We can setup a meeting with Louis-Philippe at anytime that please us.
